### ISSUE TITLE
wrangle.trimModelList 'publish' filter is erroneous

### ISSUE THREAD

**Issue by durack1** [PCMDI/climlib#6]
The [currently implemented `criteria='publish'`](https://github.com/PCMDI/climlib/blob/master/climlib/wrangle.py#L117) code is erroneous, as this prioritizes data according to the pace at which legitimate, ESGF-published data is being replicated and published locally at LLNL, rather than any  official ESGF status.

I suggest this criteria is removed, as with the current implementation, valid ESGF published data (just not locally at LLNL) is being omitted from dupe scans.

@mzelinka @pochedls

**Comment by pochedls** [comment]
Thanks @durack1. I think that the publish criteria probably removes too many files and I agree it should simply be removed from the default criteria.

**Comment by durack1** [comment]
@pochedls I would go a little further than that, and remove it altogether. Having a way to truncate your data search based on the rate at which data is being locally replicated, validated and then locally republished is meaningless when you're trying to filter out data using a "quality" criteria. To be honest there could be situations when today, data is locally replicated and published, and tomorrow at the host ESGF node the data is reported erroneous, the following day is unpublished, and a new dataset correcting the issue is published to replace it. We have no current way of updating our locally published status to reflect the fact that this is now errored data.

The way you would do that is check all data being used against the ES-DOC errata service (https://errata.es-doc.org/static/index.html?project=CMIP6) or which an API exists, so it could be scripted

**Comment by pochedls** [comment]
@durack1 publish is removed from the default. Pull the code and see if this works for you.

**Comment by durack1** [comment]
@pochedls just to make myself feel better, any issue with me renaming this `publish` -> `republish` and tweaking the docs?

**Comment by pochedls** [comment]
Hi @durack1 - I modified the documentation to day "boolean if the underlying data is the publish directories." I don't think people read this documentation, so I don't think this will ever even come up as an issue now that it is not used by default.
