### ISSUE TITLE
getFileMeta fails with CMIP6.CMIP.historical.KIOST.KIOST-ESM.r1i1p1f1.mon.tas.atmos.glb-z1-gr1

### ISSUE THREAD

**Issue by durack1** [PCMDI/climlib#9]
The following error occurs with the current implementation of `getFileMeta`:

```python
fn: /p/user_pub/xclim/CMIP6/CMIP/historical/atmos/mon/tas/CMIP6.CMIP.historical.KIOST.KIOST-ESM.r1i1p1f1.mon.tas.atmos.glb-z1-gr1.v20191106.0000000.0.xml
Traceback (most recent call last):
  File "makeRothigData.py", line 79, in <module>
    fileListTrim = trimModelList(fileList, criteria=['tpoints', 'cdate', 'ver']) #, verbose=True) ; #'publish',
  File "/export/durack1/git/climlib/climlib/wrangle.py", line 157, in trimModelList
    cdate, publish, tpoints = getFileMeta(fn)
  File "/export/durack1/git/climlib/climlib/wrangle.py", line 99, in getFileMeta
    fh = cdms2.open(fn)
  File "/export/durack1/anaconda3/envs/cdat821nompi/lib/python3.7/site-packages/cdms2/dataset.py", line 572, in openDataset
    dataset = Dataset(uri, mode, datanode, None, dpath)
  File "/export/durack1/anaconda3/envs/cdat821nompi/lib/python3.7/site-packages/cdms2/dataset.py", line 764, in __init__
    coordsaux = self._convention_.getDsetnodeAuxAxisIds(datasetNode)
  File "/export/durack1/anaconda3/envs/cdat821nompi/lib/python3.7/site-packages/cdms2/convention.py", line 149, in getDsetnodeAuxAxisIds
    domnode = dsetdict[item].getDomain()
KeyError: 'height'
```
The issue here is actually with `cdms2.open`, so figuring a workaround, or a PR for `cdms2` is another option

**Comment by pochedls** [comment]
@durack1 - this is an existing issue [here](https://github.com/CDAT/cdms/issues/421).

**Comment by durack1** [comment]
@pochedls is there a "patch" fix to omit known problems that is yet to be pushed? Referring to https://github.com/CDAT/cdms/issues/421#issuecomment-694499456

**Comment by pochedls** [comment]
Not that I am aware of.

**Comment by durack1** [comment]
@pochedls what I was referring to was the comment
> @mzelinka - I've hit this bug now, too. I have modified my trimmodellist functionality to skip these files (and print a warning for now)...

**Comment by pochedls** [comment]
This probably is something like this (not a fix):

```
try:
    ....
except:
    print('problem with: ' + fn)
```

**Comment by durack1** [comment]
> This probably is something like this (not a fix):
> 
> ```
> try:
>     ....
> except:
>     print('problem with: ' + fn)
> ```

Yep I was thinking of the same

**Comment by mzelinka** [comment]
Something along these lines will circumvent this issue in some cases:
`
    try:
        fh = cdms2.open(fn)
    except:
        # TRY A NON-CDMS2 SOLUTION:
        import xml.etree.ElementTree as ET
        tree = ET.parse(fn)
        root = tree.getroot()
        direct = root.attrib['directory']
        hh = glob.glob(direct + '/*nc')
        if len(hh)==1: # we can only do this if there is only one file:
            fh = cdms2.open(hh[0])
        else:     
            print('climlib.wrangle.getFileMeta: problem opening, file skipped:\n',fn)
            cdate, publish, tpoints = [0 for _ in range(3)]
            return cdate, publish, tpoints
`
